# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TranslationDictionariesBuilder/Protobuf/dictionary_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=TranslationDictionariesBuilder/Protobuf/dictionary_data.proto\x12\x06mydata\"o\n\x07\x44\x61taMap\x12\'\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x19.mydata.DataMap.DataEntry\x1a;\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.mydata.Values:\x02\x38\x01\"\x17\n\x06Values\x12\r\n\x05value\x18\x01 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TranslationDictionariesBuilder.Protobuf.dictionary_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAMAP_DATAENTRY._options = None
  _DATAMAP_DATAENTRY._serialized_options = b'8\001'
  _DATAMAP._serialized_start=73
  _DATAMAP._serialized_end=184
  _DATAMAP_DATAENTRY._serialized_start=125
  _DATAMAP_DATAENTRY._serialized_end=184
  _VALUES._serialized_start=186
  _VALUES._serialized_end=209
# @@protoc_insertion_point(module_scope)
